import { AppSettings } from "./types";

export const APP_NAME = "超强振幅";

export const DEFAULT_SETTINGS: AppSettings = {
  appName: APP_NAME,
  accounts: [
    {
      id: "main",
      name: "double",
      enabled: true,
      isMasterAccount: true,
      binance: {
        apiKey: "uBOX5sM6iJ8KBVdxcKhHmc75tDHisbxgRqaacR1aPKMpLegDpR4Al4fe44gpPb1Q",
        secretKey: "ujb5lLEDnkbOvfxwnevQXyDbR14lysO7rW8r2r51c0HFmc0QmYtPFdX7RbCuF66a",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:06:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: true,
          interval: "15m",
          startTime: "00:07:36.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:13:54.300",
          minVolumeM1: 500000,
          priceChangeK1: [-100, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.300",
          cooldown: 0,
          preferredMode: 'volume',
          conditions: {
            amp: { enabled: true, range: [10, 30], mode: 'high_low' },
            longShort: { enabled: true, buyEnabled: true, buy: 80, sellEnabled: true, sell: 20 },
            m: { enabled: true, range: [2980000, 1000000000] },
            fundingRateOptimization: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 40,
        maxPosition: 40000,
        tpModeBuy: 'amp',
        tpModeSell: 'amp',
        tpRatioBuy: 42,
        tpRatioSell: 42,
        tpFixedBuy: 2,
        tpFixedSell: 2,
        tpAmpBuy: 20,
        tpAmpSell: 20,
        tpEnabled: true,
        tpBuyEnabled: true,
        tpSellEnabled: true,
        slModeBuy: 'fixed',
        slModeSell: 'fixed',
        slRatioBuy: 85,
        slRatioSell: 85,
        slFixedBuy: 20,
        slFixedSell: 20,
        slAmpBuy: 85,
        slAmpSell: 85,
        slEnabled: true,
        slBuyEnabled: true,
        slSellEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 518,
        retentionThreshold: 488,
        alarmThreshold: 5,
      },
    },
    {
      id: "1",
      name: "buy10",
      enabled: true,
      isMasterAccount: false,
      binance: {
        apiKey: "WFfz4vWCElGYqMuMM6NTnTLFIdtfK8tsvqF40iTYJFKRr7pHotw36meyu8aRy4sc",
        secretKey: "5admozRhof1nJdVZe5RiUTqtxMD9LWjUfjSCJwYHdn2AghuSFLexFRCmaqvU9iZk",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:21:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:16.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:51.600",
          minVolumeM1: 500000,
          priceChangeK1: [-100, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.600",
          cooldown: 0,
          preferredMode: 'amp',
          conditions: {
            amp: { enabled: true, range: [10, 30], mode: 'high_low' },
            longShort: { enabled: true, buyEnabled: true, buy: 80, sellEnabled: false, sell: 20 },
            m: { enabled: true, range: [2980000, 1000000000] },
            fundingRateOptimization: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 40,
        maxPosition: 40000,
        tpModeBuy: 'amp',
        tpModeSell: 'amp',
        tpRatioBuy: 44,
        tpRatioSell: 44,
        tpFixedBuy: 2,
        tpFixedSell: 2,
        tpAmpBuy: 25,
        tpAmpSell: 25,
        tpEnabled: true,
        tpBuyEnabled: true,
        tpSellEnabled: true,
        slModeBuy: 'fixed',
        slModeSell: 'fixed',
        slRatioBuy: 85,
        slRatioSell: 85,
        slFixedBuy: 20,
        slFixedSell: 20,
        slAmpBuy: 85,
        slAmpSell: 85,
        slEnabled: true,
        slBuyEnabled: true,
        slSellEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 15,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 2088,
        retentionThreshold: 1988,
        alarmThreshold: 5,
      },
    },
    {
      id: "2",
      name: "buy8",
      enabled: true,
      isMasterAccount: false,
      binance: {
        apiKey: "bGsAa9qNVNXJp795BeQyN5deVPanvgOwdSdA7BPIRl307q6bfgMg78rMifvnUgu7",
        secretKey: "8ib27VAzY8Z8TxRMs0eccTKeZ5ys5wDBrtOY4fATIasEhdwZ1XinDQ09coj9NPAN",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:31:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:15:16.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:15:51.600",
          minVolumeM1: 500000,
          priceChangeK1: [-100, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:15:59.600",
          cooldown: 0,
          preferredMode: 'amp',
          conditions: {
            amp: { enabled: true, range: [8, 30], mode: 'high_low' },
            longShort: { enabled: true, buyEnabled: true, buy: 80, sellEnabled: false, sell: 20 },
            m: { enabled: true, range: [2980000, 1000000000] },
            fundingRateOptimization: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 40,
        maxPosition: 40000,
        tpModeBuy: 'amp',
        tpModeSell: 'amp',
        tpRatioBuy: 44,
        tpRatioSell: 44,
        tpFixedBuy: 2,
        tpFixedSell: 2,
        tpAmpBuy: 25,
        tpAmpSell: 25,
        tpEnabled: true,
        tpBuyEnabled: true,
        tpSellEnabled: true,
        slModeBuy: 'fixed',
        slModeSell: 'fixed',
        slRatioBuy: 85,
        slRatioSell: 85,
        slFixedBuy: 20,
        slFixedSell: 20,
        slAmpBuy: 85,
        slAmpSell: 85,
        slEnabled: true,
        slBuyEnabled: true,
        slSellEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 15,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 2088,
        retentionThreshold: 1988,
        alarmThreshold: 5,
      },
    },
  ],
  email: {
    enabled: true,
    sender: "",
    receiver: "",
    smtpServer: "",
    smtpPort: 465,
    password: "",
    minBalance: 5,
    maxConsecutiveLoss: 30000,
  },
  auth: {
    username: "admin",
    password: "Xxxxxx123!",
  },
};
